/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as CouncilorsSlugRouteImport } from "./routes/councilors.$slug"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const CouncilorsSlugRoute = CouncilorsSlugRouteImport.update({
  id: "/councilors/$slug",
  path: "/councilors/$slug",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/councilors/$slug": typeof CouncilorsSlugRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/councilors/$slug": typeof CouncilorsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/councilors/$slug": typeof CouncilorsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/councilors/$slug"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/councilors/$slug"
  id: "__root__" | "/" | "/councilors/$slug"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CouncilorsSlugRoute: typeof CouncilorsSlugRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/councilors/$slug": {
      id: "/councilors/$slug"
      path: "/councilors/$slug"
      fullPath: "/councilors/$slug"
      preLoaderRoute: typeof CouncilorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CouncilorsSlugRoute: CouncilorsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
